create table answers_provided (id serial not null, question_answer_id integer unique, created timestamp(6) not null, updated timestamp(6) not null, answer jsonb, primary key (id));
create table answers_selected (id serial not null, option_id integer not null, question_answer_id integer not null, created timestamp(6) not null, updated timestamp(6) not null, primary key (id));
create table drawers (id serial not null, ready_2_show boolean not null, created timestamp(6) not null, updated timestamp(6) not null, code varchar(16) not null unique, name_multilang jsonb, primary key (id));
create table options (id serial not null, preferred_answer boolean, ready_2_show boolean not null, created timestamp(6) not null, updated timestamp(6) not null, code varchar(16) not null unique, help_multilang jsonb, name_multilang jsonb, primary key (id));
create table question_answers (answer_provided_id integer unique, id serial not null, question_id integer not null, user_questionnaire_id integer not null, created timestamp(6) not null, updated timestamp(6) not null, primary key (id));
create table question_option_link (display_order integer not null, option_id integer not null, question_id integer not null, tenant_id integer, primary key (option_id, question_id));
create table questionnaire_step_link (display_order integer not null, questionnaire_id integer not null, step_id integer not null, tenant_id integer, primary key (questionnaire_id, step_id));
create table questionnaires (commercial_usage boolean not null, drawer_id integer not null, id serial not null, preferred_lang varchar(4), que_type varchar(4) not null, ready_2_show boolean not null, created timestamp(6) not null, updated timestamp(6) not null, code varchar(16) not null unique, url_id_name varchar(64) unique, description_multilang jsonb, name_multilang jsonb, primary key (id));
create table questions (answer_type varchar(4) not null, id serial not null, ready_2_show boolean not null, created timestamp(6) not null, updated timestamp(6) not null, code varchar(16) not null unique, question_multilang jsonb not null, title_multilang jsonb, primary key (id));
create table step_question_link (display_order integer not null, question_id integer not null, step_id integer not null, tenant_id integer, primary key (question_id, step_id));
create table steps (id serial not null, ready_2_show boolean not null, created timestamp(6) not null, updated timestamp(6) not null, name_multilang jsonb, primary key (id));
create table user_questionnaires (answer_lang varchar(4), id serial not null, progress_status varchar(4) not null, questionnaire_id integer not null, user_id integer not null, created timestamp(6) not null, updated timestamp(6) not null, ip_address varchar(16), primary key (id));
create table users (anonymous_user boolean, birthday date, gender varchar(4), id serial not null, preferred_lang varchar(4), created timestamp(6) not null, updated timestamp(6) not null, email_address varchar(64), first_name varchar(64), last_name varchar(64), login_name varchar(64) not null unique, middle_name varchar(64), password_hash varchar(255), primary key (id));
alter table if exists answers_provided add constraint FK2n1euht68tf5dfg3qyrno47x1 foreign key (question_answer_id) references question_answers;
alter table if exists answers_selected add constraint FK96rhs54v6hdd6wry8rxqgsv2r foreign key (option_id) references options;
alter table if exists answers_selected add constraint FKmeph866xxaakytw9rd88qp1l2 foreign key (question_answer_id) references question_answers;
alter table if exists question_answers add constraint FKcogw14ko0ergr4mwcnlj2o77i foreign key (answer_provided_id) references answers_provided;
alter table if exists question_answers add constraint FKrms3u35c10orgjqyw03ajd7x7 foreign key (question_id) references questions;
alter table if exists question_answers add constraint FKn6111wte52va3e6tj9m7jm9ae foreign key (user_questionnaire_id) references user_questionnaires;
alter table if exists question_option_link add constraint FKruneoj10yuu5p59i5ha9xod50 foreign key (option_id) references options;
alter table if exists question_option_link add constraint FKau3ct6qh9sftf9pk609aw46c foreign key (question_id) references questions;
alter table if exists questionnaire_step_link add constraint FKbj55j2490l4l1ru81i4hfj0r5 foreign key (questionnaire_id) references questionnaires;
alter table if exists questionnaire_step_link add constraint FKbjt6ynu3cfoehto71pigv6cvj foreign key (step_id) references steps;
alter table if exists questionnaires add constraint FK13r9cwivtee8hf7p5if35gb12 foreign key (drawer_id) references drawers;
alter table if exists step_question_link add constraint FKlx8icngud8o72mtqx2f4nxcl7 foreign key (question_id) references questions;
alter table if exists step_question_link add constraint FKidh6959xlc1ope0sueksh1lnf foreign key (step_id) references steps;
alter table if exists user_questionnaires add constraint FK5td2cdvoodaf4vhssdmyunfe5 foreign key (questionnaire_id) references questionnaires;
alter table if exists user_questionnaires add constraint FKtplr8gtchn6shrl0ejq2rfdma foreign key (user_id) references users;
